# Generated by Django 5.2.7 on 2025-10-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
